CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_NEWLIB_LIBC=y #needed for bmp581 library

# --------------
# RTT Debugging
#
# COMMENT FOR LOW POWER
#---------------
#CONFIG_PRINTK=y
#CONFIG_USE_SEGGER_RTT=y
#CONFIG_RTT_CONSOLE=y
#CONFIG_UART_CONSOLE=n

#UNCOMMENT FOR LOW POWER (RTT debugging not working anymore)
CONFIG_PM=y
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_LOG=n
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_PRINTK=n
CONFIG_PM_DEVICE=y
CONFIG_FLASH=y
CONFIG_SPI=y
CONFIG_SPI_NOR_IDLE_IN_DPD=y
CONFIG_SOC_NRF52833_QIAA=y
CONFIG_SOC_SERIES_NRF52X=y

# DEBUGGING
#CONFIG_LOG=y
#CONFIG_LOG_BACKEND_RTT=y
#CONFIG_LOG_DEFAULT_LEVEL=4
#CONFIG_ASSERT=y

CONFIG_MAIN_STACK_SIZE=4096

#CONFIG_DEBUG=y
#CONFIG_THREAD_NAME=y
#CONFIG_DEBUG_OPTIMIZATIONS=y
#CONFIG_DEBUG_THREAD_INFO=y

# --------------
# Bluetooth
#---------------
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP=y
CONFIG_BT_DEVICE_NAME="Newton N005"
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_NAME_MAX=70
CONFIG_BT_MAX_CONN=1
CONFIG_BT_LL_SW_SPLIT=y

#Device Information Service (DIS)
CONFIG_BT_DIS=y
CONFIG_BT_DIS_PNP=n
CONFIG_BT_DIS_MANUF="phyphox"
CONFIG_BT_DIS_MODEL="newton"

#Firmware Version
CONFIG_BT_DIS_FW_REV=y
CONFIG_BT_DIS_FW_REV_STR="1.0.0"

#Hardware Version
CONFIG_BT_DIS_HW_REV=y
CONFIG_BT_DIS_HW_REV_STR="1.0"

# Serial Number
CONFIG_BT_DIS_SERIAL_NUMBER=y
CONFIG_BT_DIS_SERIAL_NUMBER_STR="N0000"
CONFIG_BT_BAS=y

# Sensor
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_SPI=y
#CONFIG_SPI_ASYNC=y
# low power
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# float debugging
CONFIG_CBPRINTF_FP_SUPPORT=y

#FOTA
# Enable mcumgr.
CONFIG_ZCBOR=y
CONFIG_MCUMGR=y

# Enable most core commands.
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y

CONFIG_IMG_MANAGER=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y

#FOTANEW

# Ensure an MCUboot-compatible binary is generated.
CONFIG_BOOTLOADER_MCUBOOT=y

# Allow for large Bluetooth data packets.
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_L2CAP_TX_BUF_COUNT=10
CONFIG_BT_L2CAP_DYNAMIC_CHANNEL=y

CONFIG_BT_BUF_ACL_RX_SIZE=251

CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_TX_COUNT=10

CONFIG_BT_CTLR_RX_BUFFERS=2

CONFIG_BT_CONN_TX_MAX=10

CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_AUTO_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

CONFIG_BT_ATT_PREPARE_COUNT=2

# Enable the Bluetooth (unauthenticated) and shell mcumgr transports.
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_TRANSPORT_BT_AUTHEN=n


# Some command handlers require a large stack.
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192

CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_NEWLIB_LIBC_NANO=n

#SENSOR
CONFIG_SHTCX=y
#ADC
CONFIG_ADC=y
CONFIG_ADC_ASYNC=y
CONFIG_ADC_NRFX_SAADC=y
CONFIG_NRFX_SAADC=y

CONFIG_NEWLIB_LIBC=y

